language: node_js
sudo: false
node_js:
- 4
- 6
- 8
script:
- npm run clean
- npm run build
- npm run lint
- npm test
deploy:
  provider: npm
  email: hello@brianneisler.com
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: brianneisler/duxegg
  api_key:
    secure: 3ScfdPdbDrlDMNx/G7TY4c6OVDZyfwrhM2AszxlDRX9P2tRSHym163FjKEy9d5dLJidM/FY322QtXgH/x+FXnePTfyCoQuQ4jk25JuzYZn2zuwvTMWuteaW3vJqd2UCOeWxueu6nxfuF6fn9wi01vo/O4AEE52ZVb52U+iVCum8YJa+y0dBdze/m3PVQvZdf1q2h1zoauzBZiyPSr6lT2NhaD0cK1UKoowo1y5rb8X3NPj6i1gNoJrN6f1ALWvZxe8vC60mku7GDCGdEaTR5tZvZ60O4zn3HxlWf1IQRBY02zpN9t44+KQqZw0jYZIcxnHERwjmpeG3qlHTQuCf0Ndwyc47S7D98ItgQpVA2LYvSeZaTWDJdiatBmz9nE8YQ4MYofPweTk9GVqalt5WYel5S8NWli1z2jnpqW3cPoZRRu3Fgo66GlDp5UUouTujGQLtB+5WfSOAJ+ZkJPVMX3qS2J46YI0/VVYiZV0wjCsfZUZ7P/FT21rScNIRi41VOmZwxD11SikmFfAfuQJMuAm/112TyVLphWpnk5Zvq7OdtGqavtv0EM2EEbN5t6ov7HrSOPmra44ZEsWE7Rufev0LO7LGVnKk4B3h7ftgatJ7vWVDsTMzcE7c0+dScIDg+pzTR8GGZvERzZIUxzQCZoPHUrWewEqo3tVw2oqrecIk=
